### ISSUE TITLE
Dark mode messed up

### ISSUE THREAD

**Issue by ryanleesipes** [kewisch/birdbox-extension#14]
Dark mode in Thunderbird looks wrong for some websites.

This is Element:
![Screenshot 2024-08-18 052958](https://github.com/user-attachments/assets/1a8ee5fa-6be5-45f8-8295-3b5e6948eba7)

**Comment by kewisch** [comment]
Hmm I am not sure this is something I can directly control, this is a standard content tab. I think Thunderbird would need to indicate to the content tab that dark mode is applied, though I thought this happens automatically. You could try https://addons.thunderbird.net/de/thunderbird/addon/darkreader/ to see if things get better.

**Comment by kewisch** [comment]
Fixed in f9aaa34fc786486e31402629ce33d95d0f958526
