### ISSUE TITLE
No icon in spaces toolbar for website without favicon

### ISSUE THREAD

**Issue by gnthy** [kewisch/birdbox-extension#21]
Hello,

First of all, thank you for your extension.

I just had a problem with a site that doesn't have an associated logo (favicon or other) and so there is no icon in Thunderbird's spaces toolbar.

So I added a condition in the "if" on "line 134" in the "options.js" file.

      if ((reader.error) || (resp.status=="404")) {
        resolve(‘/images/addon.svg’);
      } else {
        resolve(reader.result);
      }
    };

I don't know if this is useful.

Kind regards,

Thierry

**Comment by kewisch** [comment]
That seems useful! Are you able to share the site by chance? I think we should set the image to null, but when creating the space default to the add-on icon in case the data is set to null.

Glad you like the add-on, how did you stumble upon it?

**Comment by kewisch** [comment]
26084c8829efceccaae35bb063472797adbe47a8
