### ISSUE TITLE
Add the "plus" button to the Spaces toolbar for easy adding of new webapps

### ISSUE THREAD

**Issue by ryanleesipes** [kewisch/birdbox-extension#22]
Add the "plus" button to the Spaces toolbar for easy adding of new webapps. It's too much effort to go into the extension menu to do it.

**Comment by kewisch** [comment]
Fun preview of things to come: 

<img width="1241" alt="image" src="https://github.com/user-attachments/assets/3cc357b5-e2dc-4e5b-9dd2-b49a2eb5bb72">

**Comment by kewisch** [comment]
Fixed for v1.2.1
