### ISSUE TITLE
Clicking links in Matrix results in a blank page

### ISSUE THREAD

**Issue by ryanleesipes** [kewisch/birdbox-extension#23]
Clicking links in Matrix chat (in a Birdbox space, of course) - results in a blank page, I must close the tab and reopen to get back to the webapp. The desired behavior is that the link is opened in the default browser (Firefox, of course).

**Comment by kewisch** [comment]
Can you check the "Internal Link Domains" setting? It should include `mozilla.modular.im`. Other links should open in Firefox.

**Comment by kewisch** [comment]
@ryanleesipes is this still happening?

**Comment by kewisch** [comment]
LMK if this comes back
